FROM rust:latest AS builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./

COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/stellar-wallet-scanner-backend /app/stellar-wallet-scanner-backend

ENV HOST=0.0.0.0
ENV PORT=80

CMD ["/app/stellar-wallet-scanner-backend"]